// license:BSD-3-Clause
// copyright-holders:David Valdeita (Seleuco) & Filipe Paulino (FlykeSpice)
/***************************************************************************

    shader_sources.hxx

    Shader sources for GLES 3.x renderer

***************************************************************************/

//=================================================
// Quad primitive program (TRUE HDR READY)
// ================================================

static const char* quad_vertex_shader_src = 
    "precision highp float;\n"
    "in float a_corner;\n"
    "in vec4 i_p0p1;\n"
    "in vec4 i_p2p3;\n"
    "in vec4 i_uv0uv1;\n"
    "in vec4 i_uv2uv3;\n"
    "in vec4 i_color;\n"
    "out vec2 v_texuv;\n"
    "out vec4 v_color;\n"
    "uniform mat4 u_ortho;\n"
    "void main() {\n"
    "    vec2 pos;\n"
    "    vec2 uv;\n"
    "    int corner = int(a_corner);\n"
    "    if (corner == 0)      { pos = i_p0p1.xy; uv = i_uv0uv1.xy; }\n"
    "    else if (corner == 1) { pos = i_p0p1.zw; uv = i_uv0uv1.zw; }\n"
    "    else if (corner == 2) { pos = i_p2p3.xy; uv = i_uv2uv3.xy; }\n"
    "    else                  { pos = i_p2p3.zw; uv = i_uv2uv3.zw; }\n"
    "    gl_Position = u_ortho * vec4(pos, 0.0, 1.0);\n"
    "    v_texuv = uv;\n"
    "    v_color = i_color;\n"
    "}\n";


static const char* quad_frag_shader_src = 
    "precision highp float;\n" 
    "in vec2 v_texuv;\n"
    "in vec4 v_color;\n"
    "uniform sampler2D s_texture;\n"
    "uniform int u_use_hdr_display;\n"
    "uniform int u_is_vector;\n"
    "uniform int u_raster_fake_hdr;\n"
    "uniform float u_raster_hdr_mult;\n"
    "uniform float u_paper_white;\n"
    "uniform float u_device_peak_multiplier;\n"
    "out vec4 fragColor;\n"
    "void main() {\n"
    "    vec4 texColor = texture(s_texture, v_texuv);\n"
    "    if (u_use_hdr_display == 1) {\n"
    "        if (u_is_vector == 1) {\n"
    "            // TRUE LINEAR PATH: Vectors and glow are already mathematically linear and calibrated\n"
    "            fragColor = vec4(texColor.rgb * v_color.rgb, texColor.a * v_color.a);\n"
    "        } else {\n"
    "            // SRGB PATH: Convert standard 8-bit textures (artworks/raster games) to Linear\n"
    "            texColor.rgb = pow(texColor.rgb, vec3(2.2));\n"
    "            vec3 linear_vcolor = pow(v_color.rgb, vec3(2.2));\n"
    "            vec3 final_sdr = texColor.rgb * linear_vcolor;\n"
    "\n"
    "            // --- RASTER PAPER WHITE CALIBRATION ---\n"
    "            float paper_white_mult = u_paper_white / 80.0;\n"
    "\n"
    "            if (u_raster_fake_hdr == 1) {\n"
    "                // --- FAKE HDR UPGRADE (Inverse Tone Mapping) ---\n"
    "                float luma = dot(final_sdr, vec3(0.2126, 0.7152, 0.0722));\n"
    "                float hdr_weight = pow(smoothstep(0.25, 1.0, luma), 2.0);\n"
    "                float current_boost = mix(1.0, u_raster_hdr_mult, hdr_weight);\n"
    "                vec3 fake_hdr = final_sdr * current_boost;\n"
    "\n"
    "                // Dynamic HDR Desaturation (Highlight Roll-off)\n"
    "                float boosted_luma = dot(fake_hdr, vec3(0.2126, 0.7152, 0.0722));\n"
    "                vec3 white_mix = vec3(boosted_luma);\n"
    "                float desat_amount = clamp(hdr_weight * (current_boost - 1.0) * 0.10, 0.0, 1.0);\n"
    "                fake_hdr = mix(fake_hdr, white_mix, desat_amount);\n"
    "\n"
    "                // --- HARDWARE DYNAMIC TONE MAPPING (Piecewise Reinhard) ---\n"
    "                // Convert Android's dynamic display capabilities to scRGB limits.\n"
    "                float hardware_peak_scRGB = (u_device_peak_multiplier * 100.0) / 80.0;\n"
    "                float max_nits_mult = max(hardware_peak_scRGB, paper_white_mult + 1.0);\n"
    "                vec3 raw_hdr_nits = fake_hdr * paper_white_mult;\n"
    "                float raw_hdr_luma = dot(raw_hdr_nits, vec3(0.2126, 0.7152, 0.0722));\n"
    "\n"
    "                // 1. Keep colors strictly linear up to Paper White (protects SDR pixel art)\n"
    "                float threshold = paper_white_mult;\n"
    "                float range = max_nits_mult - threshold;\n"
    "\n"
    "                // 2. Compress ONLY the excess HDR light into the remaining display headroom\n"
    "                float excess = max(raw_hdr_luma - threshold, 0.0);\n"
    "                float mapped_excess = (excess / (excess + range)) * range;\n"
    "                float mapped_luma = min(raw_hdr_luma, threshold) + mapped_excess;\n"
    "\n"
    "                // 3. Scale RGB proportionally by the compressed luminance to preserve hue and contrast\n"
    "                vec3 mapped_hdr = raw_hdr_nits * (mapped_luma / max(raw_hdr_luma, 0.0001));\n"
    "\n"
    "                fragColor = vec4(mapped_hdr, texColor.a * v_color.a);\n"
    "            } else {\n"
    "                // EXACT ORIGINAL HDR BEHAVIOR + PAPER WHITE\n"
    "                fragColor = vec4(final_sdr * paper_white_mult, texColor.a * v_color.a);\n"
    "            }\n"
    "        }\n"
    "    } else {\n"
    "        // CLASSIC SDR PATH\n"
    "        fragColor = texColor * v_color;\n"
    "    }\n"
    "}\n";

static const char* hdr_frag_shader_src = 
    "precision highp float;\n"
    "in vec2 v_texuv;\n"
    "in vec4 v_color;\n"
    "uniform sampler2D s_texture;\n"
    "uniform float u_exposure;\n"
    "uniform int u_use_hdr_display;\n"
    "\n"
    "// --- DYNAMIC PARAMETERS (In Physical Nits) ---\n"
    "uniform float u_base_nits;         // Target nits for standard 1.0 intensity (e.g., 300.0)\n"
    "uniform float u_max_nits;          // Physical limit of the CRT phosphor (e.g., 400.0)\n"
    "uniform float u_device_peak_nits;  // Monitor max physical capability (Passed as Nits/100, e.g., 10.0 for 1000 nits)\n"
    "\n"
    "out vec4 fragColor;\n"
    "\n"
	"void main() {\n"
    "    // 1. BEAM ENERGY FETCH (Linear Accumulation Buffer)\n"
    "    vec3 beam = texture(s_texture, v_texuv).rgb * v_color.rgb;\n"
    "\n"
    "    vec3 mapped;\n"
    "    float out_mask = 0.0;\n"
    "\n"
    "    if (u_use_hdr_display == 1) {\n"
    "        // --- HDR PATH (scRGB Linear Space) ---\n"
    "        float hardware_peak_scRGB = (u_device_peak_nits * 100.0) / 80.0;\n"
    "        float max_nits_mult = min(u_max_nits / 80.0, hardware_peak_scRGB);\n"
    "        float base_mult = u_base_nits / 80.0;\n"
    "\n"
    "        // Ensure we always have headroom for the compression curve to work gracefully\n"
    "        max_nits_mult = max(max_nits_mult, base_mult + 1.0);\n"
    "\n"
    "        // 2. LINEAR SCALING\n"
    "        vec3 raw_hdr_nits = beam * u_exposure * base_mult;\n"
    "        float raw_hdr_luma = dot(raw_hdr_nits, vec3(0.2126, 0.7152, 0.0722));\n"
    "\n"
    "        // 3. HIGHLIGHT COMPRESSION THRESHOLD (The Shoulder)\n"
    "        float threshold = base_mult * 0.75;\n"
    "\n"
    "        // 4. ANTI-FATTENING MASK (Symbiotic with Tone Mapper)\n"
    "        // Tied directly to the shoulder threshold. Exactly when the core energy\n"
    "        // reaches the point of needing compression, we carve out the background.\n"
    "        // This guarantees stability no matter what base_nits the user selects.\n"
    "        out_mask = smoothstep(threshold, threshold * 2.0, raw_hdr_luma) * 0.90;\n"
    "\n"
    "        // 5. HIGHLIGHT COMPRESSION (Piecewise Reinhard)\n"
    "        float range = max_nits_mult - threshold;\n"
    "        float excess = max(raw_hdr_luma - threshold, 0.0);\n"
    "        float mapped_excess = (excess / (excess + range)) * range;\n"
    "        float mapped_luma = min(raw_hdr_luma, threshold) + mapped_excess;\n"
    "\n"
    "        // 6. SCALE RGB PROPORTIONALLY (Preserve Hue & Saturation)\n"
    "        mapped = raw_hdr_nits * (mapped_luma / max(raw_hdr_luma, 0.0001));\n"
    "\n"
    "    } else {\n"
    "        // --- SDR PATH (8-bit Standard Displays) ---\n"
    "        vec3 raw = vec3(1.0) - exp(-beam * u_exposure);\n"
    "\n"
    "        // DISPLAY GAMMA CORRECTION (OETF)\n"
    "        mapped = pow(clamp(raw, 0.0, 1.0), vec3(1.0 / 2.2));\n"
    "\n"
    "        // In SDR, raw is already exponentiated between 0 and 1.\n"
    "        float sdr_luma = dot(raw, vec3(0.2126, 0.7152, 0.0722));\n"
    "        out_mask = smoothstep(0.1, 0.8, sdr_luma) * 0.90;\n"
    "    }\n"
    "\n"
    "    // Output the mapped color and the carving mask in the alpha channel\n"
    "    fragColor = vec4(mapped, out_mask);\n"
    "}\n";
