// license:BSD-3-Clause
// copyright-holders:David Valdeita (Seleuco) & Filipe Paulino (FlykeSpice)
/***************************************************************************

    shader_sources.hxx

    Shader sources for GLES2 renderer

***************************************************************************/


// license:BSD-3-Clause
// copyright-holders:David Valdeita (Seleuco) & Filipe Paulino (FlykeSpice)
/***************************************************************************

    shader_sources.hxx

    Shader sources for GLES renderer

***************************************************************************/


//=================================================
// Quad primitive program (TRUE HDR READY)
// ================================================

static const char* quad_vertex_shader_src = 
    "precision highp float;\n"
    "in float a_corner;\n"
    "in vec4 i_p0p1;\n"
    "in vec4 i_p2p3;\n"
    "in vec4 i_uv0uv1;\n"
    "in vec4 i_uv2uv3;\n"
    "in vec4 i_color;\n"
    "out vec2 v_texuv;\n"
    "out vec4 v_color;\n"
    "uniform mat4 u_ortho;\n"
    "void main() {\n"
    "    vec2 pos;\n"
    "    vec2 uv;\n"
    "    int corner = int(a_corner);\n"
    "    if (corner == 0)      { pos = i_p0p1.xy; uv = i_uv0uv1.xy; }\n"
    "    else if (corner == 1) { pos = i_p0p1.zw; uv = i_uv0uv1.zw; }\n"
    "    else if (corner == 2) { pos = i_p2p3.xy; uv = i_uv2uv3.xy; }\n"
    "    else                  { pos = i_p2p3.zw; uv = i_uv2uv3.zw; }\n"
    "    gl_Position = u_ortho * vec4(pos, 0.0, 1.0);\n"
    "    v_texuv = uv;\n"
    "    v_color = i_color;\n"
    "}\n";


static const char* quad_frag_shader_src = 
    "precision highp float;\n" 
    "in vec2 v_texuv;\n"
    "in vec4 v_color;\n"
    "uniform sampler2D s_texture;\n"
    "uniform int u_use_hdr_display;\n"
    "uniform int u_is_vector;\n"
    "uniform int u_raster_fake_hdr;\n"
    "uniform float u_raster_hdr_mult;\n"
    "uniform float u_paper_white;\n"
    "uniform float u_device_peak_multiplier;\n"
    "out vec4 fragColor;\n"
    "void main() {\n"
    "    vec4 texColor = texture(s_texture, v_texuv);\n"
    "    if (u_use_hdr_display == 1) {\n"
    "        if (u_is_vector == 1) {\n"
    "            // TRUE LINEAR PATH: Vectors and glow are already mathematically linear and calibrated\n"
    "            fragColor = vec4(texColor.rgb * v_color.rgb, texColor.a * v_color.a);\n"
    "        } else {\n"
    "            // SRGB PATH: Convert standard 8-bit textures (artworks/raster games) to Linear\n"
    "            texColor.rgb = pow(texColor.rgb, vec3(2.2));\n"
    "            vec3 linear_vcolor = pow(v_color.rgb, vec3(2.2));\n"
    "            vec3 final_sdr = texColor.rgb * linear_vcolor;\n"
    "\n"
    "            // --- RASTER PAPER WHITE CALIBRATION ---\n"
    "            float paper_white_mult = u_paper_white / 80.0;\n"
    "\n"
    "            if (u_raster_fake_hdr == 1) {\n"
    "                // --- FAKE HDR UPGRADE (Inverse Tone Mapping) ---\n"
    "                float luma = dot(final_sdr, vec3(0.2126, 0.7152, 0.0722));\n"
    "                float hdr_weight = pow(smoothstep(0.25, 1.0, luma), 2.0);\n"
    "                float current_boost = mix(1.0, u_raster_hdr_mult, hdr_weight);\n"
    "                vec3 fake_hdr = final_sdr * current_boost;\n"
    "\n"
    "                // Dynamic HDR Desaturation (Highlight Roll-off)\n"
    "                float boosted_luma = dot(fake_hdr, vec3(0.2126, 0.7152, 0.0722));\n"
    "                vec3 white_mix = vec3(boosted_luma);\n"
    "                float desat_amount = clamp(hdr_weight * (current_boost - 1.0) * 0.10, 0.0, 1.0);\n"
    "                fake_hdr = mix(fake_hdr, white_mix, desat_amount);\n"
    "\n"
    "                // --- HARDWARE DYNAMIC TONE MAPPING (Piecewise Reinhard) ---\n"
    "                // Convert Android's dynamic display capabilities to scRGB limits.\n"
    "                float hardware_peak_scRGB = (u_device_peak_multiplier * 100.0) / 80.0;\n"
    "                float max_nits_mult = max(hardware_peak_scRGB, paper_white_mult + 1.0);\n"
    "                vec3 raw_hdr_nits = fake_hdr * paper_white_mult;\n"
    "                float raw_hdr_luma = dot(raw_hdr_nits, vec3(0.2126, 0.7152, 0.0722));\n"
    "\n"
    "                // 1. Keep colors strictly linear up to Paper White (protects SDR pixel art)\n"
    "                float threshold = paper_white_mult;\n"
    "                float range = max_nits_mult - threshold;\n"
    "\n"
    "                // 2. Compress ONLY the excess HDR light into the remaining display headroom\n"
    "                float excess = max(raw_hdr_luma - threshold, 0.0);\n"
    "                float mapped_excess = (excess / (excess + range)) * range;\n"
    "                float mapped_luma = min(raw_hdr_luma, threshold) + mapped_excess;\n"
    "\n"
    "                // 3. Scale RGB proportionally by the compressed luminance to preserve hue and contrast\n"
    "                vec3 mapped_hdr = raw_hdr_nits * (mapped_luma / max(raw_hdr_luma, 0.0001));\n"
    "\n"
    "                fragColor = vec4(mapped_hdr, texColor.a * v_color.a);\n"
    "            } else {\n"
    "                // EXACT ORIGINAL HDR BEHAVIOR + PAPER WHITE\n"
    "                fragColor = vec4(final_sdr * paper_white_mult, texColor.a * v_color.a);\n"
    "            }\n"
    "        }\n"
    "    } else {\n"
    "        // CLASSIC SDR PATH\n"
    "        fragColor = texColor * v_color;\n"
    "    }\n"
    "}\n";

static const char* hdr_frag_shader_src = 
    "precision highp float;\n"
    "in vec2 v_texuv;\n"
    "in vec4 v_color;\n"
    "uniform sampler2D s_texture;\n"
    "uniform float u_exposure;\n"
    "uniform int u_use_hdr_display;\n"
    "\n"
    "// --- DYNAMIC PARAMETERS (In Physical Nits) ---\n"
    "uniform float u_base_nits;         // Target nits for standard 1.0 intensity (e.g., 100.0)\n"
    "uniform float u_max_nits;          // Physical limit of the CRT phosphor (e.g., 600.0)\n"
    "uniform float u_device_peak_nits;  // Monitor max physical capability (e.g., 1000.0)\n"
    "\n"
    "out vec4 fragColor;\n"
    "\n"
    "void main() {\n"
    "    // 1. BEAM ENERGY FETCH (Linear Accumulation Buffer)\n"
    "    // 'beam' represents the accumulated linear light from the rasterization phase.\n"
    "    vec3 beam = texture(s_texture, v_texuv).rgb * v_color.rgb;\n"
    "\n"
    "    vec3 mapped;\n"
    "\n"
    "    if (u_use_hdr_display == 1) {\n"
    "        // --- HDR PATH (scRGB Linear Space) ---\n"
    "        // In scRGB, a float value of 1.0 exactly equals 80 physical nits.\n"
    "\n"
    "        // Ensure we don't request more nits than the actual display can handle\n"
    "        float safe_peak_nits = min(u_max_nits, u_device_peak_nits);\n"
    "\n"
    "        // Convert target nits to scRGB float multipliers\n"
    "        float base_mult = u_base_nits / 80.0;\n"
    "        float peak_mult = safe_peak_nits / 80.0;\n"
    "\n"
    "        // 2. PRE-COMPENSATION GAIN (Calibration)\n"
    "        // We want an input beam of 1.0 to output exactly 'base_mult' after the saturation curve.\n"
    "        // The mathematical inverse of y = P * (1 - exp(-E/P)) is E = -P * log(1 - y/P).\n"
    "        // We clamp base_mult to 99% of peak_mult to prevent math errors (log of <= 0).\n"
    "        float safe_base_mult = min(base_mult, peak_mult * 0.99);\n"
    "        float gain = -peak_mult * log(1.0 - (safe_base_mult / peak_mult));\n"
    "\n"
    "        // Apply exposure and the calibration gain\n"
    "        vec3 energy = beam * u_exposure * gain;\n"
    "\n"
    "        // 3. PHYSICAL PHOSPHOR SATURATION (Exponential Model)\n"
    "        // Asymptotically compresses highlights. The more energy, the closer it gets to peak_mult\n"
    "        // without ever exceeding it, just like real CRT phosphor.\n"
    "        mapped = peak_mult * (vec3(1.0) - exp(-energy / peak_mult));\n"
    "\n"
    "    } else {\n"
    "        // --- SDR PATH (8-bit Standard Displays) ---\n"
    "\n"
    "        // Simple exponential tone mapping (keeps values strictly below 1.0)\n"
    "        vec3 raw = vec3(1.0) - exp(-beam * u_exposure);\n"
    "\n"
    "        // 4. DISPLAY GAMMA CORRECTION (OETF)\n"
    "        // Encodes the linear light into a Gamma 2.2 space so the SDR monitor displays it correctly.\n"
    "        mapped = pow(clamp(raw, 0.0, 1.0), vec3(1.0 / 2.2));\n"
    "    }\n"
    "\n"
    "    // Multiply the final mapped color by the alpha (which acts as a spatial mask/opacity)\n"
    "    fragColor = vec4(mapped, texture(s_texture, v_texuv).a * v_color.a);\n"
    "}\n";
		
